[variables]
PYTHONUNBUFFERED = "1"
PORT = "5000"

[phases.install]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-eng", "poppler-utils"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python3 app/main.py"
