[variables]
PYTHONUNBUFFERED = "1"

[phases.install]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-eng", "poppler-utils"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.deploy]
cmd = "python3 app/main.py"
